### ISSUE TITLE
[REQUEST] Can you either strip down the history or create compressed releases for new revisions ?

### ISSUE THREAD

**Issue by UtsavBalar1231** [mvaisakh/gcc-arm64#1]
As cloning with depth:1 every few weeks has became nuisance and cloning with entire history just takes away too much space. So, can you try to setup your CI for automated compressed releases that will be a lot helpful.

**Comment by sourajitk** [comment]
@UtsavBalar1231 I'll look into it to see if that's possible but imo the history isn't that important for something like this considering they're just prebuilts. Expect a resolution soon I guess. CC: @mvaisakh

**Comment by UtsavBalar1231** [comment]
This happened yesterday while setting up a new environment, this repo and arm32 repo both combined takes about 15~20GB of space (if cloned with the whole history).
Cloning took me a lot of time.

And I think that this repo history should be trimmed down. I have also seen something like this on the rust crates repo as it gets larger the maintainers usually eliminate the whole history and force pushes it.

Or leaving all this behind simple tarball XZ releases are fine as well.

**Comment by fukiame** [comment]
isnt it already possible to download a repo compressed via GitHub's builtin function?
for example, https://github.com/mvaisakh/gcc-arm64/archive/gcc-master.tar.gz would download this repo as a compressed gz tarball, without any history

**Comment by mvaisakh** [comment]
Hi, I'm really sorry for the late reply, I'll be switching to tarball based releases and repository will be archived soon.
My recent CI builds are starting to run out of space because of the huge size of this repository.
Tarballs shall be posted on the [gcc-build](https://github.com/mvaisakh/gcc-build) script repository.

**Comment by UtsavBalar1231** [comment]
I think that's a great idea, I was using the GitHub archive method until now to reduce the repo size, 

```
wget -q --show-progress --progress=dot -O /tmp/gcc-arm64.zip \
				https://github.com/mvaisakh/gcc-arm64/archive/refs/heads/gcc-master.zip
```

Tarballs will be a good alternative, thanks.

**Comment by mvaisakh** [comment]
Hi tarballs are now available in my gcc-build repository from now on. This repository will be archived and will not receive any further updates.
